### ISSUE TITLE
Illegal DP FORMAT field in output

### ISSUE THREAD

**Issue by bartcharbon** [fritzsedlazeck/Spectre#27]
The Spectre output contains a DP FORMAT field with number = 2 and type = Float
The VCF spec states that the DP FORMAT field is a reserved field of type Integer.

We run into trouble when trying to use Spectre in our pipeline and than merging it downstream with other types of variants due to this issue,

**Comment by philippesanio** [comment]
Hi @bartcharbon 

Thanks for raising that issue, 
I am currently swamped with tasks, but I am trying to come back to you asap on that regard!

Best,
Philippe

**Comment by philippesanio** [comment]
Hi @bartcharbon,

Since DP is a reserved tag in the VCF specifications, I have changed it with the commit [07e61de](https://github.com/fritzsedlazeck/Spectre/commit/07e61dec60b1eb7d133edbf62b24766ad2269696) to CD (coverage read depth). I hope this solves the problem.

The changes are currently only available in the repository. However, you can install Spectre manually by cloning the Spectre repository and installing it locally using pip:
```bash
pip install build
git clone https://github.com/fritzsedlazeck/Spectre.git
cd ./Spectre
python3 -m build
pip install dist/spectre_cnv-<VERSION>.tar.gz # replace <VERSION> with e.g. 0.2.0
```
If you encounter any further issues, please let me know!
Best, 
Philippe
